config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :clients
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :employee
  belongs_to :client
end

app/models/client.rb
class Client < ApplicationRecord
    has_many :appointments
    has_many :employees, through: :appointments 
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :appointments
    has_many :clients, through: :appointments 


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :find_appointment, only: [:show, :edit, :update, :destroy]


  def index
    @appointments = Appointment.all
  end

  def show

  end

  def new
    @appointment = Appointment.new
  end

  def create
    appointment = Appointment.find_or_create_by(appointment_params)
    redirect_to appointment_path(appointment)
  end

  def edit

  end

  def update
 
    @appointment.update(appointment_params)
    redirect_to appointment_path(@appointment)

  end
  
  def destroy
  @appointment.destroy
  # Appointment.destroy(params[:id]})
  redirect_to appointments_path
  end



    private
    def find_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:service, :employee_id, :client_id, :apt_time)
    end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

    before_action :find_client, only: [:show, :edit, :update, :destroy]

def index
    @clients = Client.all
end


def show
    @client = Client.find(params[:id])
end

def new
    client = Client.new 
end 

def create
    client = Client.find_or_create_by(client_params)
    redirect_to client_path(client)
end 


def edit
end

def update
  @client.update(client_params)
  redirect_to client_path(@client)
end

def destroy
@client.destroy
redirect_to clients_path
end



private
def find_client
  @client = Client.find(params[:id])
end

def client_params
  params.require(:client).permit(:name, :member_since)
end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController

    before_action :find_employee, only: [:show]

    def index
        @employees = Employee.all
    end 

    def show
        @employee = Employee.find(params[:id])
    end 

    def new
        @employee = Employee.create(employee_params)
      
    end 

    def create
        employee = Employee.create(employee_params)
        redirect_to employee_path(employee)
    end 
    
      def edit
      end
    
      def update
        @employee.update(employee_params)
        redirect_to employee_path(@employee)
      end
    
      def destroy 
        Employee.destroy(params[:id])
        redirect_to employees_path 
      end


    private
    def find_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :specialty)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/appointments/edit.html.erb
<h1>Edit this  Appointment</h1>

<%= form_for @appointment do |f| %>
  <%= f.label :service %>
  <%= f.text_field :service %>
  <%= f.label :apt_time %>
  <%= f.text_field :apt_time %>
<h4>Employee:</h4>
    <%= f.label :employee_id %>
    <%= f.collection_select(:employee_id, Employee.all, :id, :name) %>
<h4>Client:</h4>
    <%= f.label :client_id %>
    <%= f.collection_select(:client_id, Client.all, :id, :name) %>
    <%= f.submit %>
<% end%>

app/views/appointments/index.html.erb
<h1>All Apointments:</h1>

<% @appointments.each do |appointment|%>
<div><%= link_to appointment.apt_time, appointment_path(appointment) %></div>
<% end %>



<!-- 
APPOINTMENT ATTRIBUTES

- EMPLOYEE
- CLIENT 
- TIME 
- SERVICE  -->

app/views/appointments/new.html.erb
<h1>New Appointment</h1>

<%= form_for @appointment do |f| %>
  <%= f.label :service %>
  <%= f.text_field :service %>
  <%= f.label :apt_time %>
  <%= f.text_field :apt_time %>
<h4>Employee:</h4>
    <%= f.label :employee_id %>
    <%= f.collection_select(:employee_id, Employee.all, :id, :name) %>
<h4>Client:</h4>
    <%= f.label :client_id %>
    <%= f.collection_select(:client_id, Client.all, :id, :name) %>
    <%= f.submit %>
<% end%>

app/views/appointments/show.html.erb
<h1><%= @appointment.client.name %></h1>
<div><h2>Your appointment is scheduled for <%= @appointment.apt_time %>, for <%=@appointment.service%>, with <%= @appointment.employee.name%>.</h2></div>
<%= link_to("KILL appointment", appointment_path(@appointment), :method => :delete) %>

app/views/clients/edit.html.erb
<h1> Edit This Client: </h1>

<%= form_for @client do |c| %>
    <%= c.label "Name:" %>
    <%= c.text_field :name  %>
    <%= c.label "Specialty:" %>
    <%= c.text_field :member_since  %>
    <%=  e.submit  %>
<% end  %>

app/views/clients/index.html.erb
<h1>All Clients</h1>
<ul>
    <% @clients.each do |client| %>
     
       <li><%= link_to("#{client.name} - member since #{client.member_since}", client_path(client.id))%></li>
    <% end %>   
</ul>


<h4>Menu:</h4>
    
    <div><%= link_to "Create New Client", new_client_path %></div>

app/views/clients/new.html.erb
<h1> Create a New Client: </h1>

<%= form_for @client do |c| %>
    <%= c.label "Name:" %>
    <%= c.text_field :name  %>
    <%= c.label "Specialty:" %>
    <%= c.text_field :member_since  %>
    <%=  e.submit  %>
<% end  %>

app/views/clients/show.html.erb
<h1>Clients:</h1>

<h2><%= @client.name %><h2>
<h3>Member since: <%= @employee.member_since %></h3>

<h4>Appointments:</h4>
<div>
    <ul>
    <% @client.appointments.each do |appt| %>
        <li> <%= appt.service + " by " + appt.employee.name + " @ " + appt.apt_time %> </li>
        <% end %> 
     </ul></div>


<h4>Menu:</h4>
    <div><%= link_to "Edit this client", edit_client_path(@client) %></div>

    <div><%= link_to "Delete This Client", client_path(@client), :method => :delete %></div>
    
    <div><%= link_to "Clients Index", clients_path %></div>

app/views/employees/edit.html.erb
<h1> Edit This Employee: </h1>

<%= form_for @employee do |e| %>
    <%= e.label "Name:" %>
    <%= e.text_field :name  %>
    <%= e.label "Specialty:" %>
    <%= e.text_field :specialty  %>
    <%=  e.submit  %>
<% end  %>

app/views/employees/index.html.erb
<h1>All Employees:</h1>

<ul>
<% @employees.each do |e| %>
    <li><%= link_to e.name, employee_path(e) %></li>
<% end %>
</ul>


<h4>Menu:</h4>
    
    <div><%= link_to "Create New Employee", new_employee_path %></div>

app/views/employees/new.html.erb
<h1> Create a New Employee: </h1>

<%= form_for @employee do |e| %>
    <%= e.label "Name:" %>
    <%= e.text_field :name  %>
    <%= e.label "Specialty:" %>
    <%= e.text_field :specialty  %>
    <%=  e.submit  %>
<% end  %>

app/views/employees/show.html.erb
<h1>Employee:</h1>

<h2><%= @employee.name %><h2>
<h3>Specialty: <%= @employee.specialty %></h3>

<h4>Appointments:</h4>
<div>
    <ul>
    <% @employee.appointments.each do |appt| %>
        <li> <%= appt.service + " @ " + appt.apt_time %> </li>
        <% end %> 
     </ul>
</div>


<h4>Menu:</h4>
    <div><%= link_to "Edit this employee", edit_employee_path(@employee) %></div>

    <div><%= link_to "Delete This Employee", employee_path(@employee), :method => :delete %></div>
    
    <div><%= link_to "Employees Index", employees_path %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SalonApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>